name: Docker Image CI

on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tortuga-softworks:cerberus:latest
